[build]
command = "npm run build"
publish = "dist/"
functions = "netlify/functions"

[build.environment]
NODE_VERSION = "20.9.0"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[[redirects]]
from = "/admin"
to = "/admin/index.html"
status = 200