backend:
  name: github
  repo: BeBraveBeKind/rise-above-template
  branch: main
  base_url: https://rise-above-template.netlify.app
  auth_endpoint: /.netlify/functions/auth

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "test"
    label: "Test Collection"
    folder: "src/data/test"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }