backend:
  name: github
  repo: BeBraveBeKind/rise-above-template
  branch: main
  base_url: https://riseabovetemplate.netlify.app
  auth_endpoint: /.netlify/functions/auth

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "home"
    label: "Homepage"
    file: "src/data/home.json"
    fields:
      - { label: "Hero Title", name: "heroTitle", widget: "string" }
      - { label: "Hero Subtitle", name: "heroSubtitle", widget: "text" }

  - name: "services"
    label: "Services"
    file: "src/data/services.json"
    fields:
      - { label: "Section Title", name: "sectionTitle", widget: "string" }
      - label: "Services"
        name: "items"
        widget: "list"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }

  - name: "contact"
    label: "Contact Page"
    file: "src/data/contact.json"
    fields:
      - { label: "Headline", name: "headline", widget: "string" }
      - { label: "Subtext", name: "subtext", widget: "text" }