backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "site"
    label: "Site Settings"
    files:
      - name: "site"
        label: "Site Settings"
        file: "src/data/site.json"
        fields:
          - { label: "Site Name", name: "siteName", widget: "string" }
          - { label: "Logo Path", name: "logo", widget: "string" }
          - label: "Navigation Links"
            name: "navigation"
            widget: "list"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "Href", name: "href", widget: "string" }
          - label: "Footer Links"
            name: "footerLinks"
            widget: "list"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "Href", name: "href", widget: "string" }
              - { label: "Enabled", name: "enabled", widget: "boolean" }

  - name: "home"
    label: "Home Page"
    files:
      - name: "home"
        label: "Home Page Content"
        file: "src/data/home.json"
        fields:
          - { label: "Hero Title", name: "heroTitle", widget: "string" }
          - { label: "Hero Description", name: "heroDescription", widget: "text" }
          - label: "Features"
            name: "features"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }

  - name: "services"
    label: "Services"
    files:
      - name: "services"
        label: "Services List"
        file: "src/data/services.json"
        fields:
          - label: "Services"
            name: "services"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }